name: lint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v4.0.0
        with:
          version-file: "pyproject.toml"
          args: "check"
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v4.0.0
        with:
          version-file: "pyproject.toml"
          args: "format --check --diff"
